import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4FAFD",
  },
  content: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 28,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 22,
  },
  eyebrow: {
    color: "#1593C5",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.5,
    marginBottom: 5,
  },
  titulo: {
    color: "#0B1D2A",
    fontSize: 28,
    fontWeight: "800",
  },
  subtitulo: {
    color: "#6E818D",
    fontSize: 14,
    marginTop: 5,
    maxWidth: 260,
    lineHeight: 20,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DDF4FC",
    borderWidth: 1,
    borderColor: "#B8E6F6",
  },
  avatarText: {
    color: "#087EAC",
    fontSize: 16,
    fontWeight: "800",
  },
  heroCard: {
    backgroundColor: "#0A7FAE",
    borderRadius: 24,
    padding: 20,
    marginBottom: 26,
    shadowColor: "#0A7FAE",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 5,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  heroLabel: {
    color: "#BCEBFA",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.3,
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
    marginTop: 7,
  },
  heroBadge: {
    minWidth: 52,
    paddingHorizontal: 12,
    height: 36,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  heroBadgeText: {
    color: "#FFFFFF",
    fontWeight: "900",
    fontSize: 12,
  },
  heroTime: {
    color: "#E2F7FE",
    fontSize: 14,
    marginTop: 9,
  },
  heroDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.18)",
    marginVertical: 17,
  },
  heroFooter: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  heroFooterText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
    backgroundColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionTitle: {
    color: "#102733",
    fontSize: 19,
    fontWeight: "800",
  },
  sectionSubtitle: {
    color: "#8A9AA4",
    fontSize: 12,
    marginTop: 3,
  },
  sectionAction: {
    color: "#0C8BBB",
    fontSize: 13,
    fontWeight: "800",
  },
  equipmentGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 26,
  },
  equipmentCard: {
    width: "48%",
    minHeight: 176,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 15,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E3F0F5",
  },
  equipmentIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#E8F8FD",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  equipmentEmoji: {
    fontSize: 22,
    color: "#0B8CBB",
  },
  equipmentName: {
    color: "#132A36",
    fontSize: 16,
    fontWeight: "800",
  },
  equipmentDetail: {
    color: "#81919B",
    fontSize: 12,
    marginTop: 3,
    marginBottom: 12,
  },
  statusPill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  statusOk: {
    backgroundColor: "#E6F7EF",
  },
  statusInfo: {
    backgroundColor: "#E7F4FC",
  },
  statusWarning: {
    backgroundColor: "#FFF4DE",
  },
  statusText: {
    color: "#47626F",
    fontSize: 10,
    fontWeight: "800",
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#E3F0F5",
  },
  statValue: {
    color: "#0B87B6",
    fontSize: 18,
    fontWeight: "900",
  },
  statLabel: {
    color: "#748791",
    fontSize: 11,
    marginTop: 4,
    fontWeight: "700",
  },
  pageEyebrow: {
    color: "#1593C5",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.5,
    marginTop: 2,
    marginBottom: 6,
  },
  pageTitle: {
    color: "#0B1D2A",
    fontSize: 29,
    fontWeight: "900",
  },
  pageSubtitle: {
    color: "#748791",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
    marginBottom: 24,
  },
  lessonCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E2EFF4",
  },
  dateBox: {
    width: 58,
    height: 58,
    borderRadius: 17,
    backgroundColor: "#E7F7FD",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  dateText: {
    color: "#0B8BBA",
    fontSize: 11,
    fontWeight: "900",
    textAlign: "center",
  },
  lessonInfo: {
    flex: 1,
  },
  lessonTitle: {
    color: "#142D39",
    fontSize: 15,
    fontWeight: "800",
  },
  lessonMeta: {
    color: "#81919B",
    fontSize: 12,
    marginTop: 5,
    lineHeight: 17,
  },
  lessonArrow: {
    color: "#77A4B6",
    fontSize: 28,
    marginLeft: 6,
  },
  tipCard: {
    flexDirection: "row",
    backgroundColor: "#0D86B5",
    borderRadius: 22,
    padding: 18,
    marginTop: 10,
  },
  tipIcon: {
    fontSize: 26,
    marginRight: 13,
  },
  tipContent: {
    flex: 1,
  },
  tipTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 4,
  },
  tipText: {
    color: "#DFF7FF",
    fontSize: 12,
    lineHeight: 18,
  },
  progressHero: {
    backgroundColor: "#0B80AF",
    borderRadius: 24,
    padding: 22,
    marginBottom: 14,
  },
  progressHeroLabel: {
    color: "#BFEAF8",
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: "900",
  },
  progressHeroValue: {
    color: "#FFFFFF",
    fontSize: 36,
    fontWeight: "900",
    marginTop: 7,
  },
  progressHeroDelta: {
    color: "#DDF6FE",
    fontSize: 12,
    marginTop: 7,
    fontWeight: "700",
  },
  progressGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 14,
  },
  progressCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 17,
    borderWidth: 1,
    borderColor: "#E2EFF4",
  },
  progressCardLabel: {
    color: "#788B95",
    fontSize: 11,
    fontWeight: "700",
  },
  progressCardValue: {
    color: "#112C39",
    fontSize: 26,
    fontWeight: "900",
    marginVertical: 7,
  },
  progressCardFooter: {
    color: "#9AA8AF",
    fontSize: 11,
  },
  goalCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: "#E2EFF4",
  },
  goalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  goalTitle: {
    color: "#19323E",
    fontSize: 15,
    fontWeight: "800",
  },
  goalPercent: {
    color: "#0C8BBB",
    fontSize: 15,
    fontWeight: "900",
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: "#E7F2F6",
    overflow: "hidden",
    marginTop: 15,
  },
  progressFill: {
    width: "64%",
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#15A2D2",
  },
  goalText: {
    color: "#8798A1",
    fontSize: 12,
    marginTop: 9,
  },
  profileCard: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 24,
    marginTop: 10,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E2EFF4",
  },
  profileAvatar: {
    width: 82,
    height: 82,
    borderRadius: 28,
    backgroundColor: "#DDF5FD",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  profileAvatarText: {
    color: "#0A85B4",
    fontSize: 25,
    fontWeight: "900",
  },
  profileName: {
    color: "#102936",
    fontSize: 21,
    fontWeight: "900",
  },
  profileLevel: {
    color: "#81919B",
    fontSize: 13,
    marginTop: 5,
  },
  profileSection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#E2EFF4",
  },
  profileItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 17,
  },
  profileItemIcon: {
    fontSize: 22,
    marginRight: 13,
  },
  profileItemContent: {
    flex: 1,
  },
  profileItemTitle: {
    color: "#17313E",
    fontSize: 14,
    fontWeight: "800",
  },
  profileItemText: {
    color: "#81919B",
    fontSize: 12,
    marginTop: 3,
  },
  profileSeparator: {
    height: 1,
    backgroundColor: "#EDF3F6",
  },
  bottomNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 14,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#DDEBF1",
    shadowColor: "#17313E",
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 10,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  navIconBox: {
    minWidth: 38,
    height: 31,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 3,
  },
  navIconBoxActive: {
    backgroundColor: "#DFF5FD",
  },
  navIcon: {
    color: "#91A2AA",
    fontSize: 18,
    fontWeight: "900",
  },
  navIconActive: {
    color: "#0787B6",
  },
  navLabel: {
    color: "#91A2AA",
    fontSize: 10,
    fontWeight: "700",
  },
  navLabelActive: {
    color: "#087EAC",
    fontWeight: "900",
  },
});
